application: enxuga-enchente
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /test.*
  script: gaeunit.py

- url: /mock.*
  script: mock_site.py

- url: /photos/.*
  script: photos.py

- url: /admin/.*
  script: admin.py

- url: .*
  script: enxuga.py

